apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: abdelrahman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: abdo23/new-app-project  # Change the image here
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-route
spec:
  to:
    kind: Service
    name: app-service
  port:
    targetPort: 80

